### ISSUE TITLE
FloatingIP trys to attach even if it is already attached and results in error

### ISSUE THREAD

**Issue by Crapworks** [terraform-providers/terraform-provider-openstack#88] opened 2017-08-24 07:57 UTC
Hi there,

### Terraform Version
`Terraform v0.10.2`
`provider-openstack_v0.2.0_x4`

### Affected Resource(s)
Please list the resources as a list, for example:
- `openstack_compute_floatingip_associate_v2`

### Terraform Configuration Files
```hcl
resource "openstack_compute_floatingip_associate_v2" "fip_1" {
  count       = "${var.instance_count}"
  floating_ip = "${element(openstack_networking_floatingip_v2.fip.*.address, count.index)}"
  instance_id = "${element(openstack_compute_instance_v2.webserver.*.id, count.index)}"
}
```

On my current OpenStack provider, floating IP association works, but the resource is unable to realized in subsequent runs that the IP is still associated. Since the resource uses the compute API and check for the external IP adress in the `addresses` list returned, this isn't working for me, since the external network is not listed. Also the APIs used in this resource are mostly marked as deprecated in OpenStack. This is also stated in this comment: https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/resource_openstack_compute_floatingip_associate_v2.go#L73-L75

For me, this results in Terraform trying to associate the floating IP again, which then results in an error. I don't have that deep of an OpenStack knowledge but aren't the API options that allow for a more generic check if a floating IP is attached?

**Comment by fatmcgav** [comment] 2017-08-24 08:16
@Crapworks are you able to run Terraform in debug mode and gist the output?

`TF_LOG=debug OS_DEBUG=1 terraform...`

I think the `terraform plan` would probably be most useful. Be sure to remove any sensitive data from the output though...

**Comment by Crapworks** [comment] 2017-08-24 10:01
https://gist.github.com/Crapworks/524e935b4f69a84a898bb301a2bc609d

**Comment by fatmcgav** [comment] 2017-08-24 11:10
@Crapworks Could you also provide a copy of the server details as listed in the 'Openstack' or 'nova' cli? As would be interesting to see if they provide details about the associated floating IP or not. 

At the moment, it would appear that the behaviour is caused by your Openstack cloud not returning the 'floating_ip' details in the 'addresses' block:
```
 2017/08/24 11:52:23 [DEBUG] OpenStack Response Body: {
   "server": {
     "OS-DCF:diskConfig": "MANUAL",
     "OS-EXT-AZ:availability_zone": "eu-de-02",
     "OS-EXT-SRV-ATTR:host": "pod01.eu-de-02",
     "OS-EXT-SRV-ATTR:hypervisor_hostname": "nova002@2",
     "OS-EXT-SRV-ATTR:instance_name": "instance-0009814c",
     "OS-EXT-STS:power_state": 1,
     "OS-EXT-STS:task_state": null,
     "OS-EXT-STS:vm_state": "active",
     "OS-SRV-USG:launched_at": "2017-08-24T09:50:41.982193",
     "OS-SRV-USG:terminated_at": null,
     "accessIPv4": "",
     "accessIPv6": "",
     "addresses": {
       "terraform-network": [
         {
           "OS-EXT-IPS-MAC:mac_addr": "fa:16:3e:16:c3:ee",
           "OS-EXT-IPS:type": "fixed",
           "addr": "192.168.10.187",
           "version": 4
         }
       ]
     },
     "config_drive": "",
     "created": "2017-08-24T09:48:53Z",
     "flavor": {
       "id": "normal1",
       "links": [
         {
           "href": "https://ecs.eu-de.otc.t-systems.com:443/16d53a84a13b49529d2e2c3646691288/flavors/normal1",
           "rel": "bookmark"
         }
       ]
     },
     "hostId": "2b47b3d445951921100a1f89486b7b5ad8da36209a0d84d2a3caf6bc",
     "id": "66f5e02b-1db3-49ea-ae39-bacda71d7525",
     "image": {
       "id": "94c5c6c1-5203-4089-af6c-7c1328f0881a",
       "links": [
         {
           "href": "https://ecs.eu-de.otc.t-systems.com:443/16d53a84a13b49529d2e2c3646691288/images/94c5c6c1-5203-4089-af6c-7c1328f0881a",
           "rel": "bookmark"
         }
       ]
     },
     "key_name": "terraform-terraform_key",
     "links": [
       {
         "href": "https://ecs.eu-de.otc.t-systems.com:443/v2/16d53a84a13b49529d2e2c3646691288/servers/66f5e02b-1db3-49ea-ae39-bacda71d7525",
         "rel": "self"
       },
       {
         "href": "https://ecs.eu-de.otc.t-systems.com:443/16d53a84a13b49529d2e2c3646691288/servers/66f5e02b-1db3-49ea-ae39-bacda71d7525",
         "rel": "bookmark"
       }
     ],
     "metadata": {},
     "name": "terraform-webserver01",
     "os-extended-volumes:volumes_attached": [
       {
         "id": "696a7047-3e88-484b-849b-879334a60774"
       }
     ],
     "progress": 0,
     "security_groups": [
       {
         "name": "terraform-secgrp-web"
       }
     ],
     "status": "ACTIVE",
     "tenant_id": "16d53a84a13b49529d2e2c3646691288",
     "updated": "2017-08-24T09:50:42Z",
     "user_id": "796b4478013946ea85186a16fdf303e4"
   }
 }
```

The missing floating_ip details are then falling through this block - [resource_openstack_compute_floatingip_associate_v2.go#L131-L140](https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/resource_openstack_compute_floatingip_associate_v2.go#L131-L140) - and nulling the resource ID, causing TF to want to re-create it. 

@jtopjian Is this a scenario you've seen before?

**Comment by Crapworks** [comment] 2017-08-24 15:32
@fatmcgav I've checked with the `openstack` cli and a `openstack server show <id>` also gives you no information about attached floating IPs. A `openstack floating ip show <id>` shows you the `fixed_ip_address` of the instance it is attached to as well as the `port_id`.

**Comment by fatmcgav** [comment] 2017-08-24 15:35
@Crapworks Hmm, OK... So that affirms what TF is reporting... 

Are you able to show the TF code for how you're creating the instance as well?
Are you creating the port as a separate resource?

**Comment by Crapworks** [comment] 2017-08-24 15:50
@fatmcgav here is the code. I do not create ports via terraform explicitly.

```hcl
resource "openstack_compute_instance_v2" "webserver" {                                                                                                                                                                                                                                    
  count           = "${var.instance_count}"
  name            = "${var.project}-webserver${format("%02d", count.index+1)}"
  image_name      = "${var.image_name}"
  flavor_name     = "${var.flavor_name}"
  key_pair        = "${openstack_compute_keypair_v2.keypair.name}"
  user_data       = "${data.template_file.webserver.rendered}"
  security_groups = [
    "${openstack_compute_secgroup_v2.secgrp_web.name}"
  ]

  network {
    uuid           = "${openstack_networking_network_v2.network.id}"
    access_network = true
  }
}
```

**Comment by fatmcgav** [comment] 2017-08-24 15:54
@Crapworks OK, cool... 

This still feels like 'non-standard' behaviour to me, but I'm hoping @jtopjian will be able to weigh-in... 

Are you able to provide any more information on the underlying Openstack installation? 
Version, Nova/Neutron, customisations etc?

**Comment by Crapworks** [comment] 2017-08-24 16:02
@fatmcgav 
Oh, I am pretty sure this is non-standard. I will try to find out more about the Openstack specifics but I know that there were modifications made to it. I'm also in touch the engineers on the provider side about the same issue but I haven't gotten any feedback from them until now. So you say that there are no better ways to get the informations on TF side, I just have to be more annoying on the provider side ;)

**Comment by jtopjian** [comment] 2017-08-26 02:58
@Crapworks I looked this over and it does look a little strange. I have a few questions and comments, some of which is just rehashing what's already been said:

1. If you do `openstack --debug server show <id>`, you should see something like:

```json
{                                                
  "OS-EXT-IPS-MAC:mac_addr": "fa:16:3e:de:09:bf",
  "OS-EXT-IPS:type": "floating",                 
  "addr": "172.24.4.4",                          
  "version": 4                                   
}                                                
```

But I'm assuming you're not, correct? If so, that's definitely non-standard behavior.

2. The inline comment in `openstack_compute_floatingip_associate_v2` about deprecated APIs isn't related to this issue. The comment was about using an awkward ID of `ip/ID/ip` as the resource ID instead of calling either a deprecated API or mixing Neutron into the resource. If either of those options were used, it would break usability for the other option (ie: older nova-network environments would break _or_ it wouldn't work with newer Neutron environments).

The API call to associate a floating IP with an instance (which is what `openstack_compute_floatingip_associate_v2` is using in its Create and Delete functions) isn't deprecated.

Additionally, the API call to retrieve server information (which includes the above JSON snippet) isn't deprecated, either.

3. What happens when you run `terraform apply`? Does Terraform want to make any changes? Or is it that the `openstack_compute_instance_v2` resource isn't reporting its floating IP?

One thing to try (and I'm not sure if this would actually help, but who knows) would be to:

1. Create a Port
2. Create a Floating IP and set the `port_id` to the above Port ID.
3. Create an instance and use:

```hcl
network {
  port = "${port.id}"
}
```

Your instance probably still won't see the floating IP, but maybe attaching floating IPs to ports is how your provider intended them to be used?

**Comment by Crapworks** [comment] 2017-08-28 16:06
@jtopjian 
1. correct, this is not in the output
2. Ok, then I was mixing things up, since almost half of the nova API has currently a DEPRECATED note :)
3. Terraform apply is trying to attach the floating ip again to the server, since it doesn't find it in the `address` array, resulting in an error that the floating ip is already associated

I coudn't test the port thing yet, since my tenant is current screwed after my loadbalancer playaround (see #87) but I got a response from my provider, which simply says "this worked with Terraform 0.9.1". i was checking the corresponding code and it looks like there it just parses the server ID out of the url and checks if it matches the actual server it should be attached to.

If you can just tell me in one or two sentences why this is bad, I can report back to them. I mean I will anyways, but maybe you have more insight what can go wrong when doing it like that.

Cheers,
Christian

**Comment by jtopjian** [comment] 2017-08-28 16:15
> If you can just tell me in one or two sentences why this is bad, I can report back to them.

We're reliant on what is returned in the `addresses` field of the instance response JSON to determine what IPs are attached. If that response is being modified by the provider, then the addresses will fail to be detected.

Your provider is more than welcome to open an Issue (or jump in here) to help resolve this issue. If they know it works with 0.9.1, they might have more insight into what's going on.

**Comment by jtopjian** [comment] 2017-08-28 16:23
@Crapworks Actually, hold on. 

The error you're seeing is not related to the `openstack_compute_instance_v2` resource, it's related to the `openstack_compute_floatingip_associate_v2` resource.

Can you provide your full Terraform configuration that you're using to generate this error?

**Comment by Crapworks** [comment] 2017-08-30 09:08
@jtopjian 
A short update on the "port workaround":

Using this workaround, the instance created will fall into a faulty state. Getting server informations will show the following:

```
"fault": {                                                                                                                                                                                       
  "code": 500,                                                                                                                                                                                   
  "created": "2017-08-30T08:32:52Z",                                                                                                                                                             
  "message": "Build of instance fd6edbfe-8f87-431a-8116-e7115de6ed6c aborted: Build of instance fd6edbfe-8f87-431a-8116-e7115de6ed6c aborted: Create cascaded instance failed. update_port_precommit failed.\nNeutron server returns request_ids: ['req-8dbbae21-d06a-41f6-a02"                                                                                                                                                                                                            
},  
```

The message seems to be truncated, so I can't really tell whats going wrong here. The floating IP request also fails with:

```
"NeutronError": {                                                                                                                                                                                  
  "detail": "",                                                                                                                                                                                    
  "message": "Bad floatingip request: Cannot add floating IP to port 9064e9a6-9443-4f76-aa17-67d7ec3498ca that has no fixed IPv4 addresses.",                                                      
  "type": "BadRequest"                                                                                                                                                                             
}          
```

This is probably because of the instance failure in the first place? because I wouldn't realy want to use static  IP addresses here.

I will get you the requested information soon!

**Comment by Crapworks** [comment] 2017-08-31 09:02
@jtopjian I found out the problem and fixed it (I needed to assign the subnet to the port via the fixed_ip block) and now it works. The floating IP is recognized to be attached to the port as it seems. Although this adds quite some complexity because the user HAS to use explicit port resources and bind floating IPs and secrurity groups to it.

Here is the debug log for the apply (I removed unrelated things): https://gist.github.com/Crapworks/6e998887f9696d92ec25fa5a18f82204

The relevant configuration:

```hcl
resource "openstack_compute_instance_v2" "webserver" {
  count           = "${var.instance_count}"
  name            = "${var.project}-webserver${format("%02d", count.index+1)}"
  image_name      = "${var.image_name}"
  flavor_name     = "${var.flavor_name}"
  key_pair        = "${openstack_compute_keypair_v2.keypair.name}"
  user_data       = "${data.template_file.webserver.rendered}"
  security_groups = [
    "default",
    "${openstack_compute_secgroup_v2.secgrp_web.name}"
  ]
  network {
    uuid           = "${openstack_networking_network_v2.network.id}"
  }
}

resource "openstack_compute_floatingip_associate_v2" "fip_1" {
 count       = "${var.instance_count}"
 floating_ip = "${element(openstack_networking_floatingip_v2.fip.*.address, count.index)}"
 instance_id = "${element(openstack_compute_instance_v2.webserver.*.id, count.index)}"
}

resource "openstack_networking_floatingip_v2" "fip" {
  count = "${var.instance_count}"
  pool  = "${var.external_network}"
}
```

**Comment by jtopjian** [comment] 2017-09-03 23:54
@Crapworks Thanks for the update! As well, thank you for your patience with figuring this out.

Would you consider this issue resolved?

**Comment by Crapworks** [comment] 2017-09-04 06:52
@jtopjian Well, there is a work around using ports, although it is not a pretty one. But the main thing is that the vendor is not showing IPs from the external network on the instance. So I will close this ticket and try to do something on the provider side. Thanks!

**Comment by khdegraaf** [comment] 2017-09-27 02:31
FYI, handling this issue in the provider so you don't need to do a workaround is on my list of things to support in terraform-provider-huaweicloud that I am developing for Huawei.  I should be able to add some additional api calls in the Terraform provider to fetch this info...

**Comment by khdegraaf** [comment] 2017-10-26 00:21
I have a fix that addresses this at the provider level at https://github.com/khdegraaf/terraform-provider-opentelekomcloud.

**Comment by Crapworks** [comment] 2018-03-28 15:31
@jtopjian Hi, sorry to dig out this old thread, but I was able to convince the OTC to make their API more OpenStack compatible, so they updated their nova output:

```json
{
   "server": {
       "tenant_id": "67906cc786ac45b991bda34d467ea987",
       "addresses": {
           "test-network": [
               {
                   "OS-EXT-IPS-MAC:mac_addr": "fa:16:3e:48:7c:eb",
                   "OS-EXT-IPS:type": "fixed",
                   "addr": "192.168.10.10",
                   "version": 4
               },
               {
                   "OS-EXT-IPS-MAC:mac_addr": "fa:16:3e:48:7c:eb",
                   "OS-EXT-IPS:type": "floating",
                   "addr": "xxx.xxx.xxx.xxx",
                   "version": 4
               }
           ]
       },
```

From what I can see here:

https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/resource_openstack_compute_floatingip_associate_v2.go#L132-L140

It looks like the code should match. But I am still getting the same error. Terraform tries to attach the FIP again, which fails, since it is already attached. Is the API response still not correct?

Cheers,
Christian

**Comment by jtopjian** [comment] 2018-03-28 15:58
@Crapworks would you be able to post some new debug output?

Also, are you still using the Terraform configuration mentioned in https://github.com/terraform-providers/terraform-provider-openstack/issues/88#issuecomment-326235725?

**Comment by Crapworks** [comment] 2018-03-28 16:22
@jtopjian The configuration is still the same. I can get you the debug log tomorrow. Is a `plan` enough for you? 
I've also checked the statefile, and for the instance, the floating_ip field is empty. 
By the way, should the association resource show up in the statefile as well? Because it isn't.

**Comment by jtopjian** [comment] 2018-03-28 16:39
@Crapworks Sure, we can start with `plan`.

> I've also checked the statefile, and for the instance, the floating_ip field is empty.

That should be fine. The instance's `floating_ip` field was marked as "removed" and is no longer in use:

https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/resource_openstack_compute_instance_v2.go#L79-L83

> By the way, should the association resource show up in the statefile as well? Because it isn't.

It should, yes. If it's not, then it might not be getting created successfully?

**Comment by Crapworks** [comment] 2018-03-28 16:48
@jtopjian That's strange, since there are no error during creation time and everything gets created correctly. What could prevent the association ressource from showing up in the statefile if there isn't an error during the apply?

**Comment by jtopjian** [comment] 2018-03-28 16:50
For your situation, my guess is that it's the unsetting of the ID that's doing it:

https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/resource_openstack_compute_floatingip_associate_v2.go#L142-L144

**Comment by Crapworks** [comment] 2018-03-28 17:03
Ah, I see... But should the code find the floating ip as associated? Taking into account the nova response I've posted? Nontheless, I will get you the debug output tomorrow asap.

**Comment by jtopjian** [comment] 2018-03-28 17:09
@Crapworks Yep - that's the vicious circle we're in right now 😄 

From what I can see, the new Nova output you've shown is correct. I'm at a loss as to why it's still not working.

**Comment by Crapworks** [comment] 2018-03-29 11:20
@jtopjian After I tried again today, everything was working fine and I was almost doubting my sanity... After some tries, I realized that there is a race condition. There seems to be a 50/50 chance that the call to Nova is *NOT* going to show the external network *YET*, so the resource will not end up in the statefile (but no error is shown and all resources are marked as created).

My question to you is: does it makes sense to wait for the external network to show up in the Nova output (with a low timeout, like 5 seconds) or do you think this is not a practical solution?

**Comment by jtopjian** [comment] 2018-03-29 15:00
Nice find 😄 

> My question to you is: does it makes sense to wait for the external network to show up in the Nova output (with a low timeout, like 5 seconds) or do you think this is not a practical solution?

So you're saying during instance creation, block until the instance's `addresses` info is populated? That's a tough call. In theory an instance could exist without network information. However, we might be able to add some kind of flag to the schema to say "wait until network".

> Anyways, I think there should be some indication that something failed during creation time because it still says that the floatingip association was created successfully.

This is true. My knee-jerk reaction to this is to blame the openstack environment. These API calls should be synchronous but it feels like they're behaving in an async manner.

**Comment by Crapworks** [comment] 2018-03-29 15:31
> So you're saying during instance creation, block until the instance's addresses info is populated? That's a tough call. In theory an instance could exist without network information. However, we might be able to add some kind of flag to the schema to say "wait until network".

No, my idea was to do it here: https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/resource_openstack_compute_floatingip_associate_v2.go#L124-L140

If after this block `associated` is still false, sleep and try again. Probably something like this (although I have no idea what this actually does, due to my lack of Go skills): https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/resource_openstack_compute_instance_v2.go#L460-L469

The association ressource should associate the floating ip, so it makes sense that it waits until it is associated, or to get a timeout if it didn't work (which would also conveniently create an error message ;))

> This is true. My knee-jerk reaction to this is to blame the openstack environment. These API calls should be synchronous but it feels like they're behaving in an async manner.

Well, I absolutely agree. But as far as I understood it was already quite some hussle to get the information into the Nova output at all, since the external network in the OTC is something special, not really OpenStack-like.

This is why I was asking if it makes sense to you to implement something like that, although from your experience this is not needed for the majority of openstack installations. That said, it wouldn't hurt them as well, since they get the correct response the first time and everything continues as normal.

**Comment by jtopjian** [comment] 2018-03-29 15:53
> No, my idea was to do it here

ahh OK, I see. Yes, that's a good idea.

> That said, it wouldn't hurt them as well, since they get the correct response the first time and everything continues as normal.

Agreed.

**Comment by mvasilenko** [comment] 2018-04-24 06:59
@Crapworks hit the same issue, with incorrect handing `openstack_compute_floatingip_associate_v2`.
Using terraform with openstack provider at OpenTelekomCloud for kubespray, doesn't work well.

Can you please explain your workaround using ports with an example? Thank you.

**Comment by Crapworks** [comment] 2018-04-24 07:58
Hi @mvasilenko,

you can find OTC specific terraform examples here: https://github.com/OpenTelekomCloud/terraform-otc

Instance and Port definitions are for example here: https://github.com/OpenTelekomCloud/terraform-otc/blob/master/minimal/instances.tf
And the FloatingIP is attached to the port here: https://github.com/OpenTelekomCloud/terraform-otc/blob/master/minimal/floatingips.tf

@jtopjian 
Is somebody already working on this? If not, I can see if I can implement this with my low level Go skillz :)

**Comment by mvasilenko** [comment] 2018-04-24 14:16
what i've done is copied `contrib/terraform/openstack` to `contrib/terraform/opentelekomcloud`
and changed resource names from `openstack-*` to `opentelekomcloud-*`

the only difference i saw is `opentelekomcloud` terraform provider uses `external_gateway` in `opentelekomcloud_networking_router_v2` resource

this approach is require some changes to dynamic inventory script `hosts`  included in `kubespray`

**Comment by jtopjian** [comment] 2018-04-25 00:09
> Is somebody already working on this? If not, I can see if I can implement this with my low level Go skillz :)

I totally dropped the ball on this and I'm really sorry about that. If you wanted to try it out, I'd be glad to assist or answer any questions.

**Comment by jtopjian** [comment] 2018-05-02 03:52
Hi all,

I've just submitted #310 which might fix this problem. It hasn't been fully tested in CI yet, so there might be a bug.

If you're able to test this and confirm it resolves your problem, let me know :)

**Comment by Crapworks** [comment] 2018-05-17 13:46
Hi @jtopjian 
sorry for the delay, it wasn't easy to get some free time during the last days. I've tested your patch with 10 apply/destroy runs in a row, without any errors. So if I didn't just get extremely lucky, I would say your patch is working! :)

Thank you so much for working on this!

Cheers,
Christian

**Comment by mvasilenko** [comment] 2018-05-17 14:02
Hi @jtopjian sorry to say that, it's not working for me, but I'm testing on OpenTelekomCloud using openstack terraform provider from your PR, it assigns floating ips just fine, but don't put it terraform.tfstate. It can be linked with some opentelekomcloud-specific network features, probably, not sure.

```
            "openstack_networking_floatingip_v2.bastion": {
                    "type": "openstack_networking_floatingip_v2",
                    "depends_on": [
                        "null_resource.dummy_dependency"
                    ],
                    "primary": {
                        "id": "ef99a769-0282-4a00-8c65-8da959536390",
                        "attributes": {
                            "address": "160.44.x.x",
                            "fixed_ip": "",
                            "id": "ef99a769-0282-4a00-8c65-8da959536390",
                            "pool": "admin_external_net",
                            "port_id": "",
                            "region": "eu-de",
                            "tenant_id": "60b4a75b30e1455ca57c6d5b0e8adfcc"
                        },
                        "meta": {
                            "e2bfb730-ecaa-11e6-8f88-34363bc7c4c0": {
                                "create": 600000000000,
                                "delete": 600000000000
                            }
                        },
                        "tainted": false
                    },
                    "deposed": [],
                    "provider": "provider.openstack"
                },
```

however it's working with opentelekomcloud terraform provider

```
              "opentelekomcloud_compute_floatingip_associate_v2.bastion": {
                    "type": "opentelekomcloud_compute_floatingip_associate_v2",
                    "depends_on": [
                        "opentelekomcloud_compute_instance_v2.bastion.*"
                    ],
                    "primary": {
                        "id": "160.44.199.3/968986af-ac0d-455b-9302-cfc0db208553/",
                        "attributes": {
                            "fixed_ip": "10.0.0.136",
                            "floating_ip": "160.44.x.x",
                            "id": "160.44.x.x/968986af-ac0d-455b-9302-cfc0db208553/",
                            "instance_id": "968986af-ac0d-455b-9302-cfc0db208553",
                            "region": "eu-de"
                        },
                        "meta": {},
                       "tainted": false
                    },
                    "deposed": [],
                    "provider": "provider.opentelekomcloud"
                },
```

@Crapworks just curios, what is your test env - cloud, provider, can you share your code?

**Comment by Crapworks** [comment] 2018-05-17 14:05
@mvasilenko did you set "wait_until_associated" to true in you association resource? It is not completely clear if you don't look at the code that you need to add a new property. I am testing against the OTC as well.

**Comment by mvasilenko** [comment] 2018-05-17 14:26
@Crapworks sorry, i've totally missed it, now it's working fine, thank you.
@jtopjian thank you for you patch!

**Closed** 2018-05-17 14:30 UTC
Labels: bug

**Comment by Crapworks** [comment] 2018-06-13 09:56
@jtopjian Do you have any idea when this is going to be released?

**Comment by jtopjian** [comment] 2018-06-20 15:00
@Crapworks A new release is out with this feature included. Please let me know if you have any problems or questions :)

**Comment by Crapworks** [comment] 2018-07-02 08:01
@jtopjian thanks for the update! I've been working with the new release for a while now and everything works fine! Thank you again for your work!
