### ISSUE TITLE
OpenStack instance is re-created to apply state change (if the network interface connected to it is detached)

### ISSUE THREAD

**Issue by jayaprakashr** [terraform-providers/terraform-provider-openstack#137] opened 2017-10-26 12:26 UTC
Incase of any state change to the openstack_compute_instance_v2 resource, Terraform re-creates the instance because of which I lost all my data associated with the instance.  For example, **if  I remove an network interface from Openstack instance manually  which has 3 interfaces attached** and then if I do terraform plan & apply it destroys the instance and creates a new one.

**Actual Behavior:**
It destroys the instance and re-creates a new instance to address the state change. Because of which I lost all my data.

**Expected Behavior:**
It should re-attach the interface to the compute instance without recreating the instance. 

**Openstack instance resource template**

```
{
        "resource": {
                "openstack_compute_instance_v2": {
                        "Director": {
                                "flavor_name": "${var.flavor}",
                                "image_name": "${var.image}",
                                "key_pair": "${var.key_pair}",
                                "name": "Director_Terraform",
                                "network": [{
                                                "name": "${var.inband_network}"
                                        },
                                        {
                                                "name": "${var.public_network}"
                                        },
                                        {
                                                "name": "${var.local_network}"
                                        }
                                ],
                                "security_groups": [
                                        "${var.security_groups}"
                                ],
                                "user_data": "${data.template_file.vd.rendered}"
                        }
                }
        }
}
```

**Comment by jtopjian** [comment] 2017-10-26 13:34
>  Incase of any state change to the openstack_compute_instance_v2 resource, Terraform re-creates the instance

This is expected and correct behavior. Modifying resources outside of Terraform is not recommended. 

Additionally, Terraform does not yet have support to attach and detach interfaces from an instance, so in this specific case, it's impossible for Terraform to re-attach the interface.

But in general, resources created by Terraform should only be managed and maintained by Terraform.

I'm going to close this issue since it's not a bug, but please let me know if you have any questions.

**Closed by jtopjian** 2017-10-26 13:34 UTC

**Comment by jtopjian** [comment] 2017-10-26 13:42
Quick note:

If you _must_ modify a resource outside of Terraform, the best course of action is to try manually editing the state file to reflect the changes. This is sometimes a common task in Terraform.

Of course, it would be wonderful if Terraform could react to all changes and correct them without destruction of the instance, but if you take the general case of:

1. I used Terraform to create resources
2. I modified those resources outside of Terraform

It's almost impossible for Terraform to know every possible combination of change and react accordingly (even if there was support to do such remedy). How would Terraform be able to understand _why_ you made a change, the exact method of making the change, and then correctly reverse that change?

But on the topic of attaching and detaching interfaces: if that's a use-case that you have for use within Terraform, meaning:

1. Use Terraform to create an instance
2. Modify the Terraform config to remove an interface
3. Modify the Terraform config to attach an interface

Then a feature request of attachment/detachment of interfaces is certainly valid :)

Again, let me know if you have any questions or need any clarification.

**Comment by jayaprakashr** [comment] 2017-10-26 13:43
Thanks @jtopjian 

`But in general, resources created by Terraform should only be managed and maintained by Terraform.
`
How about doing the same change (removing 1 network interface) in **Terraform template**, and then executing terraform plan/apply. In this case even if we re-configure through terraform, it re-creates the instance. Which shouldn't be the case right ?

I'm looking for the list of attributes that Terraform supports to apply the change alone to Openstack compute resource instead of re-creation.

**Comment by jtopjian** [comment] 2017-10-26 13:44
> I'm looking for the list of attributes that Terraform supports to apply the change alone to Openstack compute resource instead of re-creation.

This _should_ be in the documentation. If it's not, then it's a doc bug and please report it.

Also, running `terraform plan` will tell you if Terraform will destroy a resource due to a change.

**Comment by jayaprakashr** [comment] 2017-10-28 03:47
`This should be in the documentation. If it's not, then it's a doc bug and please report it.
`

Its created and the issue id - https://github.com/hashicorp/terraform-website/issues/44

**Comment by jtopjian** [comment] 2017-10-28 14:54
@jayaprakashr You can open issues related to OpenStack documentation in this Github repository. The documentation for the OpenStack provider is maintained in this repository as well.

https://github.com/terraform-providers/terraform-provider-openstack/tree/master/website

Focusing on the `openstack_compute_instance_v2` resource specifically:

https://www.terraform.io/docs/providers/openstack/r/compute_instance_v2.html

If you search for the phrase "Changing this creates a new server", you'll see that it's listed for several attributes, including the "network" attribute which is what caused your instance to be recreated.

**Comment by jayaprakashr** [comment] 2017-11-02 05:25
thanks @jtopjian
