### ISSUE TITLE
Error creating OpenStack project: Resource not found

### ISSUE THREAD

**Issue by ntmggr** [terraform-providers/terraform-provider-openstack#239] opened 2018-02-11 20:01 UTC
### Terraform Version
Terraform v0.11.3
+ provider.openstack v1.2.0
+ provider.template v1.0.0

### Affected Resource(s)
Please list the resources as a list, for example:
* openstack_identity_project_v3.tenant_project: Error creating OpenStack project: Resource not found

### Terraform Configuration Files
```
provider "openstack" {
  user_name   = "xxxxxxxxxx"
  domain_name = "default"
  tenant_name = "admin"
  password    = "xxxxxxxxxx"
  auth_url    = "http://localhost:5000/v2.0"
  region      = "RegionOne"
}

resource "openstack_identity_project_v3" "tenant_project" {
  name = "${var.tenant}"
  description = "${var.tenant}"
  enabled     = true
  is_domain   = false
  parent_id   = ""
}
variable tenant {
  description = "Openstack tenant to use"
  default = ""
}
```
Terraform.tfvars
```
tenant                     = "tftest"
```

### Debug Output
https://gist.github.com/ntmggr/482db2e1e4ea8bddcafdb350573e0ed9

### Panic Output
N/A

### Expected Behavior
It should have created a new project called `tftest`

### Actual Behavior
Error: Error applying plan:

1 error(s) occurred:

* openstack_identity_project_v3.tenant_project: 1 error(s) occurred:

* openstack_identity_project_v3.tenant_project: Error creating OpenStack project: Resource not found

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Running in Openstack Newton

**Comment by ntmggr** [comment] 2018-02-11 20:08
The problem is related to this 
```
2018-02-11T21:56:21.928+0200 [DEBUG] plugin.terraform-provider-openstack_v1.2.0_x4: 2018/02/11 21:56:21 [DEBUG] OpenStack Request URL: POST http://keystone.XXXXXXXX.internal:5000/v2.0/v3/projects
``` 
as somehow the provider tries to connect to the wrong url.

I did try setting the provider auth_url to `auth_url    = "http://localhost:5000` instead of `auth_url    = "http://localhost:5000/v2.0` with no luck

**Comment by jtopjian** [comment] 2018-02-11 20:13
@ntmggr I believe the problem is that you're authenticating to Keystone v2 but the Identity resources are only compatible with Keystone v3 (hence the v3 in the name).

Do you know if the OpenStack environment supports Keystone v3?

**Comment by ntmggr** [comment] 2018-02-11 20:54
@jtopjian thanks for coming back.

Yes it does.

**Comment by jtopjian** [comment] 2018-02-11 22:25
@ntmggr I recommend changing the auth url to use `/v3` instead of `/v2.0`. That should help.

**Comment by ntmggr** [comment] 2018-02-23 13:49
@jtopjian this does not help either. same issue

**Comment by jtopjian** [comment] 2018-02-23 16:07
@ntmggr OK, can you provide the output (with `OS_DEBUG=1`) when using `/v3` where appropriate?

**Comment by n00bjs** [comment] 2018-04-18 23:12
@jtopjian having identical problem 
### Terraform Version
Terraform v0.11.7
provider.openstack v1.3.0

### provider.tf
```
provider "openstack" {
  user_name = "${var.openstack_user_name}"
  tenant_name = "${var.openstack_tenant_name}"
  password  = "${var.openstack_password}"
  auth_url  = "${var.openstack_auth_url}"
}
```
### deploy.tf
```
resource "openstack_identity_project_v3" "project_1" {
  name = "${var.openstack_new_tenant_name}"
  description = "A sample terraform project"
  domain_id = "Default"
}
```
### Debug Output
https://gist.github.com/n00bjs/07a3164911ab3e6cd1c8a9764a800f0c

somehow It tries to connect to 
[DEBUG] OpenStack Request URL: POST http://10.103.64.3:5000/v2.0/v3/projects

**Comment by jtopjian** [comment] 2018-04-19 03:26
@n00bjs Thanks for reporting the issue. I think I see the problem: my guess is that your OpenStack catalog is publishing a `/v2.0` endpoint for the identity service?

If so, I've spotted an upstream bug that will cause the endpoint URL to be malformed to `/v2.0/v3`.

I'll look at getting this fixed.

**Comment by jtopjian** [comment] 2018-04-24 02:49
Quick status update on this: I have some pending PRs into Gophercloud which will resolve this issue. I hope to get them merged and into Terraform soon. However, it might be another week or two. I apologize for the delay.

**Closed** 2018-05-11 15:08 UTC
Labels: bug, upstream
