### ISSUE TITLE
You must provide exactly one of DomainID or DomainName in a Scope with ProjectName

### ISSUE THREAD

**Issue by xczhang07** [terraform-providers/terraform-provider-openstack#372] opened 2018-07-19 01:56 UTC
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.11.7
+ provider.null v1.0.0
+ provider.openstack v1.6.0

our firm use terraform, it works well in under a directory "A" , then I decide to create a new project on our internal git, then I move all the files under "A" to the new directory "B", after move, I run terraform init, terraform plan, then I got the following error:
xc_ubuntu1604@Ubuntu:~/terraform_test$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

Error: Error refreshing state: 1 error(s) occurred:

* provider.openstack: You must provide exactly one of DomainID or DomainName to authenticate by Username

below is my rc.sh file:

```
#!/usr/bin/env bash

# To use an OpenStack cloud you need to authenticate against the Identity
# service named keystone, which returns a **Token** and **Service Catalog**.
# The catalog contains the endpoints for all services the user/tenant has
# access to - such as Compute, Image Service, Identity, Object Storage, Block
# Storage, and Networking (code-named nova, glance, keystone, swift,
# cinder, and neutron).
#
# *NOTE*: Using the 2.0 *Identity API* does not necessarily mean any other
# OpenStack API is version 2.0. For example, your cloud provider may implement
# Image API v1.1, Block Storage API v2, and Compute API v2.0. OS_AUTH_URL is
# only for the Identity API served through keystone.
export OS_AUTH_URL=https://vio.lab.fp.f5net.com:5000/v3

# With the addition of Keystone we have standardized on the term **tenant**
# as the entity that owns the resources.
export OS_TENANT_ID=ea0ac7b11aab4f9ebba6d1ec9eddd2ee
export OS_TENANT_NAME="xizhang"

# unsetting v3 items in case set
unset OS_PROJECT_ID
unset OS_PROJECT_NAME
unset OS_USER_DOMAIN_NAME

# In addition to the owning entity (tenant), OpenStack stores the entity
# performing the action as the **user**.
export OS_USERNAME="xizhang"

# With Keystone you pass the keystone password.
echo "Please enter your OpenStack Password: "
read -sr OS_PASSWORD_INPUT
export OS_PASSWORD=$OS_PASSWORD_INPUT

# If your configuration has multiple regions, we set that information here.
# OS_REGION_NAME is optional and only valid in certain environments.
export OS_REGION_NAME="nova"
# Don't leave a blank variable, unset it if it was empty
if [ -z "$OS_REGION_NAME" ]; then unset OS_REGION_NAME; fi

export OS_ENDPOINT_TYPE=publicURL
export OS_INTERFACE=public
export OS_IDENTITY_API_VERSION=2
```

does anyone know how to fix this issue?

Thx
XC

**Comment by jtopjian** [comment] 2018-07-19 02:18
@xczhang07 

> our firm use terraform, it works well in under a directory "A" , then I decide to create a new project on our internal git, then I move all the files under "A" to the new directory "B", after move, I run terraform init, terraform plan, then I got the following error:

This is most likely due to some authentication changes that happened in a recent release.

It looks like the issue is that you're specifying an Identity v3 auth url:



```
export OS_AUTH_URL=https://vio.lab.fp.f5net.com:5000/v3
```

But your rc file is requesting v2:

```
export OS_IDENTITY_API_VERSION=2
```

Try setting `OS_AUTH_URL` to `https://vio.lab.fp.f5net.com:5000/v2.0`

If that doesn't work, try downloading a v3-compatible openrc file from the OpenStack dashboard (if your cloud provider has this). 

If this doesn't work, you might want to contact the cloud's admins for help on what settings you need in order to authenticate correctly.

**Comment by xczhang07** [comment] 2018-07-19 22:04
hello, it does not work with your solution...

**Comment by jtopjian** [comment] 2018-07-20 03:47
@xczhang07 What is the error message you see when `OS_AUTH_URL` is set to `https://vio.lab.fp.f5net.com:5000/v2.0`?

**Comment by xczhang07** [comment] 2018-07-21 16:32
@jtopjian , I resolve this issue because of the .terraform directory is hide and not copy to the new directory, do you know when we generate the ".terraform" directory?

**Comment by jtopjian** [comment] 2018-07-21 16:47
The `.terraform` directory is created when you run either `terraform init`, `apply`, etc. It contains various files, including the plugins (such as the OpenStack provider), which is downloaded when you run `terraform init`.

The reason that copying the `.terraform` directory worked for you is because you have copied an older version of the OpenStack plugin which is somehow allowing your rc file to work.

If your satisfied with this solution, then I'm going to close this issue. However, I still believe your rc file contains errors which are going to prevent it from working with newer versions of the OpenStack provider.

**Closed by jtopjian** 2018-07-21 16:47 UTC

**Comment by xczhang07** [comment] 2018-07-21 16:50
@jtopjian Hello ,thanks for your replying, yeap, I agree with you, current solution is only a work around solution. I have tried to run terraform init in the new directory; however, it seems does not work, but how to change the rc file, I tried to google it, I do not get too much useful information.


Thx
