### ISSUE TITLE
openstack_lb_member_v2 - wrong 'new resource required' info

### ISSUE THREAD

**Issue by pszypowicz** [terraform-providers/terraform-provider-openstack#268] opened 2018-03-20 13:59 UTC
When issuing `terraform apply` on already existing stack I got member resource recreation. For some reason it does not save proper subnet_id in terraform.tfstate

### Terraform Version
Terraform v0.11.4
+ provider.openstack v1.2.0

### Affected Resource(s)
openstack_lb_member_v2

### Debug Output
```$ terraform apply
[...]
-/+ openstack_lb_member_v2.nginx[0] (new resource required)
      id:                         "0519f674-2ac9-46cb-a21e-a3444b286f85" => <computed> (forces new resource)
      address:                    "192.168.36.3" => "192.168.36.3"
      admin_state_up:             "true" => "true"
      name:                       "0519f674-2ac9-46cb-a21e-a3444b286f85" => ""
      pool_id:                    "0c5eb7ba-2f81-4021-af70-c7abd465884a" => "0c5eb7ba-2f81-4021-af70-c7abd465884a"
      protocol_port:              "80" => "80"
      region:                     "" => <computed>
      subnet_id:                  "" => "8a3e7c3f-7b19-4c1b-ab39-c33c7dd4cf96" (forces new resource)
      tenant_id:                  "e8afe2a914254a9199eea5ae1357d0bb" => <computed>
      weight:                     "1" => <computed>

-/+ openstack_lb_member_v2.nginx[1] (new resource required)
      id:                         "27648c03-43f2-40a0-ab18-08a9f29e352e" => <computed> (forces new resource)
      address:                    "192.168.36.4" => "192.168.36.4"
      admin_state_up:             "true" => "true"
      name:                       "27648c03-43f2-40a0-ab18-08a9f29e352e" => ""
      pool_id:                    "0c5eb7ba-2f81-4021-af70-c7abd465884a" => "0c5eb7ba-2f81-4021-af70-c7abd465884a"
      protocol_port:              "80" => "80"
      region:                     "" => <computed>
      subnet_id:                  "" => "8a3e7c3f-7b19-4c1b-ab39-c33c7dd4cf96" (forces new resource)
      tenant_id:                  "e8afe2a914254a9199eea5ae1357d0bb" => <computed>
      weight:                     "1" => <computed>
```

### Expected Behavior
subnet is the same, so it should not be recreated

### Actual Behavior
Member is being recreated

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Openstack with OpenContrail

**Comment by jtopjian** [comment] 2018-03-20 15:38
@pszypowicz Thanks for reporting the issue.

Can you please provide the terraform configuration (the contents of your `main.tf` file) that is triggering this issue? As well, we might need to see the debug output:

```shell
$ OS_DEBUG=1 TF_LOG=DEBUG terraform apply
```

And copy the above (sanitized) output to a gist.

> Openstack with OpenContrail

Just a quick note about this: we've run into a few issues before which were caused by bugs in the OpenContrail plugin specifically.

**Comment by rruu** [comment] 2018-08-04 19:50
Same problem. Try to change volume_size in app01 instance.

[main.ft](https://gist.github.com/rruu/44dd2502189822b2e7d236776481a939) - provider & instance app01

[debug](https://gist.github.com/rruu/383b0940aae1f35c5355ce563d35653e) - OS_DEBUG=1 TF_LOG=DEBUG terraform apply

**Comment by jtopjian** [comment] 2018-08-07 02:41
@rruu Thank you for reporting this, but this is a separate issue altogether.

Changing the `volume_size` in a block device will cause the instance to be rebuilt. This is expected behavior and not something that we can change.

If you want to boot an instance from a volume and change the volume size, you _might_ be able to do this by [booting from an existing volume](https://www.terraform.io/docs/providers/openstack/r/compute_instance_v2.html#boot-from-an-existing-volume). You can create the volume with the `openstack_blockstorage_volume_v3` resource which has [early support for volume resizing](https://www.terraform.io/docs/providers/openstack/r/blockstorage_volume_v3.html#enable_online_resize) but it is only supported in a few OpenStack clouds (you'll need to check with your OpenStack cloud admins/support to verify).

**Comment by rruu** [comment] 2018-08-07 17:13
@jtopjian 
thx,
Adding instance to config will cause the instance to be rebuilt too?
https://gist.github.com/rruu/48fda0e86733af4d513abfb63ba44639

**Comment by jtopjian** [comment] 2018-08-07 17:40
@rruu I don't understand what you mean - can you clarify?

**Comment by rruu** [comment] 2018-08-07 18:00
@jtopjian I have 1 instance (app01)
https://gist.github.com/rruu/44dd2502189822b2e7d236776481a939

then i add new instance ```resource "openstack_compute_instance_v2" "app02"..``` and apply, first (app01) resource recreated ``(new resource required)```

**Comment by jtopjian** [comment] 2018-08-07 18:13
@rruu Adding a new instance to your configuration should not cause other instances to be rebuilt. More than likely you have changed something in your original instance that is causing it to be rebuilt -- the second instance has no relation to the first.

If you have additional issues you'd like to discuss, it might be best to open a new issue as this issue (#268) is specifically about the Load Balancing Member resource.

**Comment by kayrus** [comment] 2019-01-08 17:01
I had a similar situation, when used count for compute resources. When I tried to scale up or scale down, all pool members were recreated.

**Comment by jtopjian** [comment] 2019-01-20 05:13
@kayrus Thank you for confirming. I'm going to close this issue then since that should resolve the reported problem. However, I will reopen it if further discussion is needed or if that's not fully resolving the reported problem.

**Closed by jtopjian** 2019-01-20 05:13 UTC
