### ISSUE TITLE
openstack_images_image_v2 does not set property

### ISSUE THREAD

**Issue by moio** [terraform-providers/terraform-provider-openstack#289] opened 2018-04-17 13:30 UTC
### Terraform Version
Latest 0.11.7, with latest openstack provider 1.3.

### Affected Resource(s)

- openstack_images_image_v2

### Terraform Configuration Files

Relevant parts pasted below:

```hcl
resource "openstack_images_image_v2" "images" {
  name = "${element(var.images, count.index)}"
  image_source_url = "${var.image_locations["${element(var.images, count.index)}"]}"
  count = "${length(var.images)}"
  container_format = "bare"
  disk_format = "qcow2"
  properties {
    hw_rng_model = "virtio"
  }
}```

Variables are defined as follows:

```hcl
variable "images" {
  description = "list of images to be uploaded to Glance, leave default for all"
  default = ["centos7", "opensuse423"]
  type = "list"
}

variable "image_locations" {
  description = "list of locations to download images, override to add custom ones"
  default = {
    centos7 = "http://w3.nue.suse.com/~smoioli/sumaform-images/openstack/centos7.qcow2"
    opensuse423 = "https://download.opensuse.org/repositories/systemsmanagement:/sumaform:/images:/openstack/images/opensuse423.x86_64.qcow2"
  }
  type = "map"
}
```

### Debug Output
https://gist.github.com/moio/cf242b87b84ca2aa186ec08b1fb96f80

### Expected Behavior

Image property `hw_rng_model` should be set to `virtio`, at next terraform plan nothing should be done.

### Actual Behavior

Image property `hw_rng_model` is not set and next terraform plan signals the change again.

Note that setting the property via the `openstack` client works, provided it is specified in single quotes:

```
openstack image set --property hw_rng_model='virtio' <UUID>
```

### Steps to Reproduce
1. `terraform apply`

**Comment by jtopjian** [comment] 2018-04-17 20:05
@moio Thank you for reporting this. I _think_ I fixed this issue upstream a few days ago, coincidentally. I should have a fix for this shortly.

**Comment by moio** [comment] 2018-04-18 05:58
If there is any patch I could test I am happy to volunteer verifying them! Thanks!

**Comment by jtopjian** [comment] 2018-04-18 14:52
@moio I was unable to reproduce the issue you're seeing with the config you provided, but I've opened #292 which _might_ fix the problem. 

If you're able to test it out, that would definitely help! Let me know if you need help compiling it.

**Comment by jtopjian** [comment] 2018-05-01 15:32
@moio Version 1.4 of this provider was just released. Let me know if it helps at all or if you're still seeing this issue. :)

**Comment by jtopjian** [comment] 2018-05-07 15:41
@moio No problem.

Can you run the following and provide the output to a github gist (please make sure to remove any sensitive information)?

```
OS_DEBUG=1 TF_LOG=DEBUG terraform apply
```

I'm not able to reproduce this problem myself, so I'll need to review logs (with `OS_DEBUG`) in order to further look at this.

**Comment by moio** [comment] 2018-05-10 06:42
https://gist.github.com/moio/5157a9a149c5f9a1fd0f5a1979f2e448

**Comment by jtopjian** [comment] 2018-08-17 02:07
@moio I apologize for the lack of activity on this.

I recently made some adjustments to the image resource. While looking into another issue, I realized that updating properties on the image is not actually supported. Any changes were either made only to the state or would have subsequent `apply`'s show the change needed to be made.

This is most likely the core cause of the problem you're seeing.

The only possible solution at this time is to set `properties` to `ForceNew`. So when a property is changed, a new image will be created. This is not the best behavior since it _is_ possible to update properties on images. But this is not currently supported in the upstream Gophercloud library.

The image resource should have handled this better from the start. I hope that we can eventually get the resource to behave as normal in the near future.

Creating images with initial properties is still supported and works.

Please let me know if you have any questions.

**Comment by jtopjian** [comment] 2018-08-17 03:47
@moio Actually "in the near future" should mean "in the next release" if all goes well.

I've got this working and will have a PR soon.

**Comment by jtopjian** [comment] 2018-09-06 01:49
@moio 1.9.0 was released today which _should_ fix this problem. Please let me know if you're still having issues, though.

**Closed by jtopjian** 2018-09-06 01:49 UTC
Labels: bug

**Comment by moio** [comment] 2018-09-25 07:40
I confirm the issue was perfectly solved.

Thanks for the fix and again sorry for those very late responses!
