### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by abuisine** [terraform-providers/terraform-provider-openstack#506] opened 2018-12-05 09:56 UTC
### Terraform Version
```
Terraform version: 0.11.10
provider.openstack: version = "~> 1.10"
```
### Affected Resource(s)
- openstack_compute_instance_v2

### Terraform Configuration Files
I am not ready to share my tf plan, yet

### Panic Output
https://gist.github.com/abuisine/3a381a9f435ee23ad40710f71b185668

### Steps to Reproduce
terraform apply or destroy

### Important Factoids
Openstack version : Pike

### References

**Comment by jtopjian** [comment] 2018-12-06 02:44
@abuisine Thank you for reporting this.

My guess is that this is most likely an issue with the OpenStack cloud you're using. For some reason, the network information is not being retrieved correctly.

You might be able to reproduce this with a more simple test of just launching a single `openstack_compute_instance_v2` resource.

If you're able to reproduce this with a single instance, can you please provide the output of:

```shell
$ TF_LOG=DEBUG OS_DEBUG=1 terraform apply
```

That should help us better determine why the crash is happening. If it turns out this is due to some kind of customization the cloud provider has done, there might be some workarounds we can suggest. But just to be realistic: sometimes there's not much we can do when a cloud provider has made customizations (this provider only guarantees support for unmodified OpenStack environments).

**Comment by abuisine** [comment] 2018-12-06 09:46
Thanks for you quick feedback.
I am unfortunately not able to reproduce the problem since I solved it through a bunch of manipulations (reducing the number of instances to zero in my plan, modifying the plan, manually deleting assets through the openstack api/horizon)

As far as I am aware, the underlying openstack is vanilla pike, no special binary of any form ... I know it does not help that much as comment :P

I propose to close this ticket, which I will re-open if I face the issue again, with the added log options

**Comment by till** [comment] 2018-12-17 16:49
@jtopjian I just opened another ticket — just noticed it's very similar: #541

**Comment by jtopjian** [comment] 2018-12-23 07:02
I'm going to close this in favor of #541. Both issues are related and #541 has more details about the cause.

**Closed by jtopjian** 2018-12-23 07:02 UTC
