### ISSUE TITLE
Volume V2: Unable to destroyed volume attached via openstack_compute_volume_attach_v2

### ISSUE THREAD

**Issue by samcarpentier** [terraform-providers/terraform-provider-openstack#639] opened 2019-01-24 01:02 UTC
Hi,

I am encountering an issue with _openstack_compute_volume_attach_v2_ and/or _openstack_blockstorage_volume_v2_.

Once a _openstack_blockstorage_volume_v2_ has been attached to a compute instance via the _openstack_compute_volume_attach_v2_ resource, running `terraform destroy` returns the following error:

```
Error: Error applying plan:

1 error(s) occurred:

* openstack_blockstorage_volume_v2.myvol (destroy): 1 error(s) occurred:

* openstack_blockstorage_volume_v2.myvol: Error detaching openstack_blockstorage_volume_v2 f95e268e-d57d-401d-9132-0af08ebebbb0 from 653a0f69-a561-4faf-9800-09416bd3444d: Resource not found
```

### Terraform Version

```
[samcarpentier@MBP ~]$ terraform -v
Terraform v0.11.11
+ provider.openstack v1.14.0
```

### Affected Resource(s)

- openstack_blockstorage_volume_v2
- openstack_compute_volume_attach_v2

### Terraform Configuration Files
```hcl
provider "openstack" {
  auth_url         = "${var.auth_url}"
  tenant_name      = "${var.tenant_name}"
  region           = "${var.region}"
  user_domain_name = "${var.user_domain_name}"
}

resource "openstack_blockstorage_volume_v2" "myvol" {
  name = "myvol"
  size = 1
}

resource "openstack_compute_instance_v2" "myinstance" {
  name        = "myinstance"
  image_id    = "3210d2d3-601a-4d94-b299-bfaeb27f47bc"
  flavor_name = "m1.small"

  network {
    uuid = "1f93c662-04d4-44ec-9e59-c2315497c0a2"
  }
}

resource "openstack_compute_volume_attach_v2" "attached" {
  instance_id = "${openstack_compute_instance_v2.myinstance.id}"
  volume_id   = "${openstack_blockstorage_volume_v2.myvol.id}"
}
```

### Debug Output

https://gist.github.com/samcarpentier/c6d79175ece1971cb01716a8f889523a

### Expected Behavior

The _openstack_blockstorage_volume_v2_ should be destroyed correctly when used with the _openstack_compute_volume_attach_v2_ resource.

### Actual Behavior

The _openstack_blockstorage_volume_v2_ resource is not being destroyed and Terraform is returning the error mentioned above.

Running `terraform destroy` a second time after the error occurs destroys the remaining _openstack_blockstorage_volume_v2_ correctly without any error.

### Steps to Reproduce

1. Copy the above Terraform configuration
2. Run `terraform apply`
3. Run `terraform destroy` - the error occurs
4. Run `terraform destroy` again - the _openstack_blockstorage_volume_v2_ is successfully deleted

### References

- #16 
- https://github.com/hashicorp/terraform/issues/8030

**Comment by jtopjian** [comment] 2019-01-24 02:43
@samcarpentier Thank you for reporting this. I think I know what the issue is and have opened #640 to resolve it. If you're able to test this and confirm, it would help to confirm the fix is valid, but no problem at all if you aren't able to test.

**Comment by samcarpentier** [comment] 2019-01-24 13:04
@jtopjian I can confirm that your PR fixed the issue. All resources are getting properly created and destroyed.

```
[samcarpentier@MBP ~]$ tf destroy
openstack_compute_instance_v2.myinstance: Refreshing state... (ID: c1108f11-2d35-4123-bcc6-1c54e3320573)
openstack_blockstorage_volume_v2.myvol: Refreshing state... (ID: 17bbdb5f-7eab-4ee4-8ea8-70b1cfeea723)
openstack_compute_volume_attach_v2.attached: Refreshing state... (ID: c1108f11-2d35-4123-bcc6-1c54e3320573/17bbdb5f-7eab-4ee4-8ea8-70b1cfeea723)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  - openstack_blockstorage_volume_v2.myvol

  - openstack_compute_instance_v2.myinstance

  - openstack_compute_volume_attach_v2.attached


Plan: 0 to add, 0 to change, 3 to destroy.

Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

openstack_compute_volume_attach_v2.attached: Destroying... (ID: c1108f11-2d35-4123-bcc6-1c54e3320573/17bbdb5f-7eab-4ee4-8ea8-70b1cfeea723)
openstack_compute_volume_attach_v2.attached: Destruction complete after 10s
openstack_compute_instance_v2.myinstance: Destroying... (ID: c1108f11-2d35-4123-bcc6-1c54e3320573)
openstack_blockstorage_volume_v2.myvol: Destroying... (ID: 17bbdb5f-7eab-4ee4-8ea8-70b1cfeea723)
openstack_blockstorage_volume_v2.myvol: Destruction complete after 1s
openstack_compute_instance_v2.myinstance: Still destroying... (ID: c1108f11-2d35-4123-bcc6-1c54e3320573, 10s elapsed)
openstack_compute_instance_v2.myinstance: Destruction complete after 11s

Destroy complete! Resources: 3 destroyed.
```

Lightning fast response time!

**Comment by samcarpentier** [comment] 2019-01-24 19:36
@jtopjian Thank you very much for the very quick implementation.

Is there somewhere where I could find your roadmap or the release schedule?

**Comment by jtopjian** [comment] 2019-01-24 19:37
> Is a place where I could find your roadmap or the release schedule?

We don't have a standard schedule, but we've got a good amount of fixes queued up, so probably within the next week.

However, I re-opened this because I just realized I only got 50% of the fix correct. I'm going to open a new PR shortly with the completed implementation.

**Comment by jtopjian** [comment] 2019-01-24 19:46
@samcarpentier I've opened #641 which is the correct implementation of this. If you have a moment, can you verify this one? I apologize about that.

**Comment by samcarpentier** [comment] 2019-01-24 21:01
@jtopjian No problem at all! I will take a couple of minutes to test this one tomorrow morning.

**Comment by jtopjian** [comment] 2019-01-25 18:46
> The second fix works properly as well. However, it looks like it broke some unit tests!

Thank you so much for confirming again! The unit test error is ignorable - both Travis and OpenLab run the unit tests, so if only 1 fails, it's a temporary issue.

**Comment by jtopjian** [comment] 2019-02-12 03:40
@samcarpentier I apologize for the late reply. #641 was merged and it's been released.

Thank you so much for reporting this and testing the fix!

**Closed by jtopjian** 2019-02-12 03:40 UTC
Labels: bug
