### ISSUE TITLE
authentication worked in 1.3.0 but fails in 1.4.0

### ISSUE THREAD

**Issue by jrandall** [terraform-providers/terraform-provider-openstack#311] opened 2018-05-02 14:52 UTC
### Terraform Version
```
$ terraform -v
Terraform v0.11.7
```

### Affected Resource(s)
All openstack_ resources and data sources.

### Debug Output
Relevant output is:
```
2018/05/02 14:44:02 [ERROR] root: eval: *terraform.EvalConfigProvider, err: You must provide exactly one of DomainID or DomainName in a Scope with ProjectName
2018/05/02 14:44:02 [ERROR] root: eval: *terraform.EvalSequence, err: You must provide exactly one of DomainID or DomainName in a Scope with ProjectName
2018/05/02 14:44:02 [ERROR] root: eval: *terraform.EvalOpFilter, err: You must provide exactly one of DomainID or DomainName in a Scope with ProjectName
2018/05/02 14:44:02 [ERROR] root: eval: *terraform.EvalSequence, err: You must provide exactly one of DomainID or DomainName in a Scope with ProjectName
2018/05/02 14:44:02 [TRACE] [walkRefresh] Exiting eval tree: provider.openstack
```

### Expected Behavior
v1.4.0 should work with existing configurations that worked with v.1.3.0. 

### Actual Behavior
WIth v.1.40, auth failed with the error message:
```
Error: Error refreshing state: 1 error(s) occurred:

* provider.openstack: You must provide exactly one of DomainID or DomainName in a Scope with ProjectName
```

### Important Factoids
This issue can be solved (in our environment) by setting an additional environment variable: `OS_PROJECT_DOMAIN_NAME=Default`

Note that with v1.3.0, the `OS_` vars we had set (and were working) were:
 - `OS_AUTH_URL`
 - `OS_USERNAME`
 - `OS_PASSWORD`
 - `OS_PROJECT_NAME`
 - `OS_USER_DOMAIN_NAME`

With v.1.4.0, it appears we need to set:
 - `OS_AUTH_URL`
 - `OS_USERNAME`
 - `OS_PASSWORD`
 - `OS_PROJECT_NAME`
 - `OS_USER_DOMAIN_NAME`
 - `OS_PROJECT_DOMAIN_NAME`

**Comment by jtopjian** [comment] 2018-05-02 14:59
@jrandall This was an intentional change with the 1.4 release to more closely align with other OpenStack applications. 

You should be able to use the credentials / settings in a standard openrc file (downloaded from the OpenStack dashboard) to authenticate. 

This might require changing the authentication options in the `provider` block of your configuration, but that should be the only change needed. This should not be destructive in any way. It sounds like this is the situation you're hitting?

**Comment by colin-nolan** [comment] 2018-05-03 08:32
@jtopjian the issue is that this is a breaking change in a minor version release. We expected that a configuration that worked in 1.3, would work in work in 1.4.

**Comment by jtopjian** [comment] 2018-05-03 16:08
First and foremost, I apologize for the inconvenience this is causing you folks.

The changes made were:

* Newly created authentication arguments of `user_domain_name`, `user_domain_id`, `project_domain_name`, and `project_domain_id` were added. Adding arguments is not a breaking change.
* The environment variables which these arguments read from their original incorrect placement of `domain_name` and `domain_id` to the newly created, corrected arguments.

Our analysis was that the only way this change would cause disruption to users is if an incorrect environment variable was being used previously. That environment variable would then be read by a new authentication field and a scoping error would occur. This sounds exactly what is happening here.

This change resolved several bugs being reported for users who were unable to log in using the credentials provided to them by their cloud providers. In fact, this bug was preventing entire public OpenStack clouds from cleanly working with Terraform.

This change was tested across five different clouds by two developers with different forms of authentication and no issues were seen. Of course we realize that there will be edge cases because of this change and we will definitely provide support for this.

My understanding, from what has been provided, is that you folks are hitting an issue where an environment variable is now being set in the new argument and you need to change your auth settings. To that, I absolutely do sympathize. I understand that your workflows have become reliant upon that configuration and this is disruptive. 

From reading the provided information, you were previously setting `OS_USER_DOMAIN_NAME`. While this worked before, it should actually never have worked. The reason it was working before is that `OS_USER_DOMAIN_NAME` was being squashed, along with other `OS_*_DOMAIN_*` variables into the default `OS_DOMAIN_ID` and `OS_DOMAIN_NAME` settings. This should have never been done in the provider.

The error message you're getting is correct: you need to provide a domain name or ID (either by setting `OS_PROJECT_DOMAIN_NAME` or `OS_DOMAIN_NAME`) when authenticating with a project. `OS_USER_DOMAIN_*` scopes a user to a domain, not a project.

After setting `OS_PROJECT_DOMAIN_NAME` or `OS_DOMAIN_NAME`, my guess is that you can unset `OS_USER_DOMAIN_NAME` entirely and still authenticate.

Again, I do understand that this has caused disruption. Please let me know this analysis is incorrect or if you'd like to continue discussing this.

**Comment by posox** [comment] 2018-05-04 13:29
Same problem.

I use Keystone V2 credentials with 1.3 plugin version.
After upgrading to 1.4 I cannot use Keystone V2 credentials, only V3.

**Comment by jtopjian** [comment] 2018-05-04 14:28
@posox This sounds like a different problem. The changes made were for Keystone v3 only. Keystone v2 was tested and confirmed to work.

Can you please provide (sanitized) version of what you're using to authenticate with? If you can, please also post the result of

```
OS_DEBUG=1 TF_LOG=DEBUG terraform apply
```

to a Github gist (again, please make sure to remove any sensitive information).

We'll try to sort out the issue here.

**Comment by jtopjian** [comment] 2018-05-04 15:59
@posox No worries. Thanks for the info. I'll take a look and see if I can figure out the issue. :)

**Comment by jtopjian** [comment] 2018-05-04 16:15
@posox I see the problem. 

I'm quite sure if you do:

```
OS_IDENTITY_API_VERSION=2.0
```

It'll start working again. 

This is a bug in the new upstream authentication code. I'll get this fixed.

We're going to have a short release cycle for version 1.5, so this will be released within the next 7-10 days.

**Comment by jtopjian** [comment] 2018-05-05 01:51
@posox This has been fixed in master. If you'd like to compile from source, the fix will be included. But if not, we'll have a release out the week after next.

I apologize for the inconvenience for this. The core error was my fault personally -- an oversight of only validating `2.0` for v2 and not `2` as well.

I'm going to leave this issue opened as a general catch-all for any further auth issues.

**Comment by posox** [comment] 2018-05-07 12:57
@jtopjian thank you for fixing the problem!

**Comment by jtopjian** [comment] 2018-05-22 21:17
@jrandall @colin-nolan Someone else reported a similar issue in #267.  I found this really strange and took a deep dive into the OpenStack client tools to figure out what's going on.

It turns out that the OpenStack CLI is setting `project_domain_id` to `default` if necessary. You can see the details of it here: #267.

I've opened #329 as a possible fix. If it's merged, this will cause behavior to go back to what you previously saw. I wanted to let you know this for two reasons:

1. I _think_ this is the core reason why you folks never had to set a project domain ID before (not just in Terraform, but in general).
2. If you've changed your workflows to account for this, you might again see a failure in a future release.

**Comment by jtopjian** [comment] 2018-08-02 01:15
Just a heads up that #329 has been merged. This adds support for a fall-back default domain which mirrors a hard-coded behavior in the OpenStack Python SDKs. 

Local testing has shown this works, but please let me know if this causes any issues.

I'm hopeful that this is the last authentication modification that will need to happen and Terraform now works the exact same as the Python-based OpenStack tools and their largely undocumented authentication behavior.

**Comment by jtopjian** [comment] 2018-08-09 03:40
Version 1.8.0 was released today which added the above-mentioned support for the `default_domain`. I believe that should be the last fix needed to get this Terraform provider fully on-par with how the OpenStack Python tools and SDK works.

However, please let me know if any problems arise and we'll get them fixed quickly. Reporting issues across various clouds is crucial for us to get this perfect.

I appreciate everyone's patience with this as it's been sorted out.

**Comment by jtopjian** [comment] 2018-10-08 19:54
We've gone through a number of releases and there haven't been any further reported issues, so I'm going to close this issue.

Thank you all again for your help and patience with this.

**Closed by jtopjian** 2018-10-08 19:54 UTC
