### ISSUE TITLE
openstack_compute_instance_v2 creation broken since 0.10.0

### ISSUE THREAD

**Issue by michalmedvecky** [terraform-providers/terraform-provider-openstack#64] opened 2017-08-09 19:01 UTC
### Terraform Version

Terraform v0.10.0

terraform-provider-openstack_v0.1.0_x4

### Affected Resource(s)
Please list the resources as a list, for example:
- openstack_compute_instance_v2

### Terraform Configuration Files
```hcl

resource "openstack_networking_port_v2" "pam_vip" {
  name = "pam.${var.domain}"
  network_id = "${openstack_networking_network_v2.net-lb.id}"
  admin_state_up = "true"
}

resource "openstack_networking_port_v2" "pamlb_port_lb" {
  name = "pamlb0${count.index+1}.${var.domain}"
  count = "${lookup(var.server_counts,"pam")}"
  admin_state_up = "true"
  network_id = "${openstack_networking_network_v2.net-lb.id}"
  allowed_address_pairs = {
    ip_address = "${openstack_networking_port_v2.pam_vip.all_fixed_ips.0}"
  }
}

resource "openstack_compute_instance_v2" "pam" {
  depends_on = ["openstack_networking_port_v2.pam_vip"]
  name = "pam0${count.index+1}.${var.domain}"
  count = "${lookup(var.server_counts,"pam")}"
  image_id = "${lookup(var.images,"pam")}"
  flavor_name = "${lookup(var.flavors,"pam")}"
  key_pair = "${var.keypair}"
  availability_zone = "sec"

  network {
    port = "${openstack_networking_port_v2.pamlb_port_lb.*.id[count.index]}"
  }

}
```

### Debug Output
```
openstack_compute_instance_v2.pam.1: Creating...
  access_ip_v4:                      "" => "<computed>"
  access_ip_v6:                      "" => "<computed>"
  all_metadata.%:                    "" => "<computed>"
  availability_zone:                 "" => "sec"
  flavor_id:                         "" => "<computed>"
  flavor_name:                       "" => "m3.medium"
  force_delete:                      "" => "false"
  image_id:                          "" => "66ae409c-f2ea-4a8c-a25c-3859d79f9f33"
  image_name:                        "" => "<computed>"
  key_pair:                          "" => "misko"
  metadata.%:                        "" => "3"
  metadata.ansible_keepalived_state: "" => "BACKUP"
  metadata.ansible_keepalived_vip:   "" => "10.235.2.222"
  metadata.tags:                     "" => "pam,lb,lb-pam,lb-pam-backend,iam-sandbox"
  name:                              "" => "pam02.sandbox.in.mycompany.eu"
  network.#:                         "" => "1"
  network.0.access_network:          "" => "false"
  network.0.fixed_ip_v4:             "" => "<computed>"
  network.0.fixed_ip_v6:             "" => "<computed>"
  network.0.floating_ip:             "" => "<computed>"
  network.0.mac:                     "" => "<computed>"
  network.0.name:                    "" => "<computed>"
  network.0.port:                    "" => "cd57f75b-a518-47f4-acfa-9b670f153cf8"
  network.0.uuid:                    "" => "<computed>"
  region:                            "" => "<computed>"
  security_groups.#:                 "" => "<computed>"
  stop_before_destroy:               "" => "false"
openstack_compute_instance_v2.pam.0: Destruction complete
openstack_compute_instance_v2.pam.0: Creating...
  access_ip_v4:                      "" => "<computed>"
  access_ip_v6:                      "" => "<computed>"
  all_metadata.%:                    "" => "<computed>"
  availability_zone:                 "" => "sec"
  flavor_id:                         "" => "<computed>"
  flavor_name:                       "" => "m3.medium"
  force_delete:                      "" => "false"
  image_id:                          "" => "66ae409c-f2ea-4a8c-a25c-3859d79f9f33"
  image_name:                        "" => "<computed>"
  key_pair:                          "" => "misko"
  metadata.%:                        "" => "3"
  metadata.ansible_keepalived_state: "" => "BACKUP"
  metadata.ansible_keepalived_vip:   "" => "10.235.2.222"
  metadata.tags:                     "" => "pam,lb,lb-pam,lb-pam-backend,iam-sandbox"
  name:                              "" => "pam01.sandbox.in.mycompany.eu"
  network.#:                         "" => "1"
  network.0.access_network:          "" => "false"
  network.0.fixed_ip_v4:             "" => "<computed>"
  network.0.fixed_ip_v6:             "" => "<computed>"
  network.0.floating_ip:             "" => "<computed>"
  network.0.mac:                     "" => "<computed>"
  network.0.name:                    "" => "<computed>"
  network.0.port:                    "" => "6084f989-8a89-42dd-86de-77f66b791dd6"
  network.0.uuid:                    "" => "<computed>"
  region:                            "" => "<computed>"
  security_groups.#:                 "" => "<computed>"
  stop_before_destroy:               "" => "false"
Error applying plan:

2 error(s) occurred:

* openstack_compute_instance_v2.pam[1]: 1 error(s) occurred:

* openstack_compute_instance_v2.pam.1: Error creating OpenStack server: Expected HTTP response code [201 202] when accessing [POST http://100.127.20.16:8774/v2/4a7d3b5645254117af1d36c4eb5201a5/servers], but got 409 instead
{"conflictingRequest": {"message": "Multiple possible networks found, use a Network ID to be more specific.", "code": 409}}
* openstack_compute_instance_v2.pam[0]: 1 error(s) occurred:

* openstack_compute_instance_v2.pam.0: Error creating OpenStack server: Expected HTTP response code [201 202] when accessing [POST http://100.127.20.16:8774/v2/4a7d3b5645254117af1d36c4eb5201a5/servers], but got 409 instead
{"conflictingRequest": {"message": "Multiple possible networks found, use a Network ID to be more specific.", "code": 409}}

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

With 0.9.6 works well:

```
openstack_compute_instance_v2.pam.0: Creating...
  access_ip_v4:                      "" => "<computed>"
  access_ip_v6:                      "" => "<computed>"
  all_metadata.%:                    "" => "<computed>"
  availability_zone:                 "" => "sec"
  flavor_id:                         "" => "<computed>"
  flavor_name:                       "" => "m3.medium"
  force_delete:                      "" => "false"
  image_id:                          "" => "66ae409c-f2ea-4a8c-a25c-3859d79f9f33"
  image_name:                        "" => "<computed>"
  key_pair:                          "" => "misko"
  metadata.%:                        "" => "3"
  metadata.ansible_keepalived_state: "" => "BACKUP"
  metadata.ansible_keepalived_vip:   "" => "10.235.2.222"
  metadata.tags:                     "" => "pam,lb,lb-pam,lb-pam-backend,iam-sandbox"
  name:                              "" => "pam01.sandbox.in.mycompany.eu"
  network.#:                         "" => "1"
  network.0.access_network:          "" => "false"
  network.0.fixed_ip_v4:             "" => "<computed>"
  network.0.fixed_ip_v6:             "" => "<computed>"
  network.0.floating_ip:             "" => "<computed>"
  network.0.mac:                     "" => "<computed>"
  network.0.name:                    "" => "<computed>"
  network.0.port:                    "" => "6084f989-8a89-42dd-86de-77f66b791dd6"
  network.0.uuid:                    "" => "<computed>"
  region:                            "" => "RegionOne"
  security_groups.#:                 "" => "<computed>"
  stop_before_destroy:               "" => "false"
openstack_compute_instance_v2.pam.1: Creating...
  access_ip_v4:                      "" => "<computed>"
  access_ip_v6:                      "" => "<computed>"
  all_metadata.%:                    "" => "<computed>"
  availability_zone:                 "" => "sec"
  flavor_id:                         "" => "<computed>"
  flavor_name:                       "" => "m3.medium"
  force_delete:                      "" => "false"
  image_id:                          "" => "66ae409c-f2ea-4a8c-a25c-3859d79f9f33"
  image_name:                        "" => "<computed>"
  key_pair:                          "" => "misko"
  metadata.%:                        "" => "3"
  metadata.ansible_keepalived_state: "" => "BACKUP"
  metadata.ansible_keepalived_vip:   "" => "10.235.2.222"
  metadata.tags:                     "" => "pam,lb,lb-pam,lb-pam-backend,iam-sandbox"
  name:                              "" => "pam02.sandbox.in.mycompany.eu"
  network.#:                         "" => "1"
  network.0.access_network:          "" => "false"
  network.0.fixed_ip_v4:             "" => "<computed>"
  network.0.fixed_ip_v6:             "" => "<computed>"
  network.0.floating_ip:             "" => "<computed>"
  network.0.mac:                     "" => "<computed>"
  network.0.name:                    "" => "<computed>"
  network.0.port:                    "" => "cd57f75b-a518-47f4-acfa-9b670f153cf8"
  network.0.uuid:                    "" => "<computed>"
  region:                            "" => "RegionOne"
  security_groups.#:                 "" => "<computed>"
  stop_before_destroy:               "" => "false"
openstack_compute_instance_v2.pam.0: Still creating... (10s elapsed)
openstack_compute_instance_v2.pam.1: Still creating... (10s elapsed)
openstack_compute_instance_v2.pam.0: Still creating... (20s elapsed)
openstack_compute_instance_v2.pam.1: Still creating... (20s elapsed)
openstack_compute_instance_v2.pam.0: Still creating... (30s elapsed)
openstack_compute_instance_v2.pam.1: Still creating... (30s elapsed)
openstack_compute_instance_v2.pam.1: Creation complete (ID: 32a80c00-e9d4-463d-b46e-1711463285c8)
openstack_compute_instance_v2.pam.0: Creation complete (ID: c7f2aaa0-2199-4363-9242-96e47c3707ee)

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path:
```

### Expected Behavior

Instances should be created

### Actual Behavior

Instances are not created :)

### Steps to Reproduce
1. `terraform apply`

**Comment by fatmcgav** [comment] 2017-08-09 19:39
@michalmedvecky in order to help diagnosis, are you able to run Terraform in debug mode and gist the log?
`TF_LOG=debug OS_DEBUG=1 terraform apply`

Be sure to strip out any sensitive data such as passwords, etc... 

Cheers

**Comment by jtopjian** [comment] 2017-08-09 19:43
I don't think there's a need for debug information. This might be enough to go on:

```
* openstack_compute_instance_v2.pam[1]: 1 error(s) occurred:

* openstack_compute_instance_v2.pam.1: Error creating OpenStack server: Expected HTTP response code [201 202] when accessing [POST http://100.127.20.16:8774/v2/4a7d3b5645254117af1d36c4eb5201a5/servers], but got 409 instead
{"conflictingRequest": {"message": "Multiple possible networks found, use a Network ID to be more specific.", "code": 409}}
* openstack_compute_instance_v2.pam[0]: 1 error(s) occurred:

* openstack_compute_instance_v2.pam.0: Error creating OpenStack server: Expected HTTP response code [201 202] when accessing [POST http://100.127.20.16:8774/v2/4a7d3b5645254117af1d36c4eb5201a5/servers], but got 409 instead
{"conflictingRequest": {"message": "Multiple possible networks found, use a Network ID to be more specific.", "code": 409}}
```

**Comment by michalmedvecky** [comment] 2017-08-09 19:52
np. https://gist.github.com/michalmedvecky/ab0199b6f8c84a9caf84a747cac92bfb

**Comment by fatmcgav** [comment] 2017-08-09 20:26
@michalmedvecky Cheers for the quick response. 

I've had a look at the code, and it looks like the scenario you're encountering, with only specifying a port ID, has been fixed in master in #39.

Are you able to compile the openstack provider from source and give that a go?
If not, we should be cutting a new release in the next few days, once a final couple of PR's are merged in... So it should work after that :)

**Comment by michalmedvecky** [comment] 2017-08-09 20:29
I prefer not compiling anything, I'll rather wait for the new release.

My very first touch with 0.10.0 was negative though, will wait with upgrading my toolchain :)

**Comment by fatmcgav** [comment] 2017-08-09 20:32
@michalmedvecky No worries... 

Yeh, there's a lot of change in 0.10.0, so it's a more disruptive upgrade than previous... It'll bring greater benefits down the line though :) 

I'll be sure to update this issue once the new release is out :)

**Comment by lblackstone** [comment] 2017-08-11 22:40
I confirmed that this bug is fixed on the master branch (tested with f8f0687f94b3c81482cb29102959e0ed74d8c886).

**Comment by fatmcgav** [comment] 2017-08-13 19:01
@lblackstone Cheers for the confirmation.

**Comment by jtopjian** [comment] 2017-08-15 01:36
@lblackstone indeed - thanks!

@michalmedvecky A new version of this provider was released today. I'm going to close this issue since it has been confirmed to be fixed, but do let us know if you still see this problem.

As well, please continue to open bug reports for any other issues you find -- we really appreciate the feedback.

**Closed by jtopjian** 2017-08-15 01:36 UTC
Labels: bug

**Comment by michalmedvecky** [comment] 2017-08-22 11:33
Please, is it possible to specify particular provider version required within my .tf definitions? If I run terraform-0.10.0 init, then do some work and then call terraform init when newer version is released, the older is kept.

**Comment by michalmedvecky** [comment] 2017-08-22 11:39
Btw I can confirm with 0.2.0 the problem does not appear anymore (with the original code :-)

**Comment by fatmcgav** [comment] 2017-08-22 11:56
@michalmedvecky Cheers for the update. 

Yeh, it is possible to specify the required provider version. https://www.terraform.io/docs/configuration/providers.html gives more details. 

Cheers
