### ISSUE TITLE
Diff does not match

### ISSUE THREAD

**Issue by xocasdashdash** [terraform-providers/terraform-provider-openstack#279] opened 2018-04-11 22:22 UTC
### Terraform Version

```
Terraform v0.11.6
+ provider.null v1.0.0
+ provider.openstack v1.3.0
+ provider.random v1.2.0
+ provider.template v1.0.0
```

### Terraform Configuration Files
This is the config that is triggering the crash
```hcl

  scheduler_hints {
    group = "${var.instance_group}"
  }

  metadata = "${merge(
            map("managed", "true", "name", "${var.number_of_instances == 1 ? upper(var.instance_name) : "${upper(var.instance_name)}-${count.index+1}"}", "group", "managed_instances","az", "${var.availability_zone == "" ? 
    lookup(var.availability_zone_map, element(
      split(",",var.availability_zones[var.datacenter_name]), (count.index+random_integer.az_start.result) % length(split(",",var.availability_zones[var.datacenter_name]))
      ))
     : var.availability_zone
  }"),var.extra_metadata)}"
```
It first started happening when I added the scheduler_hints variable and now it's happening with the metadata map.
### Debug Output
I can't produce it, if I re-run terraform plan it tries to nuke the current infra and recreate it, exactly like if i had tainted it. It should have done that when I added the random az, but it didn't and know it is picking up that change. 

### Crash Output
https://gist.github.com/xocasdashdash/e13b1083f34bddb6cdb7a9227c16c07a
### Expected Behavior
Terraform should have picked up the availability zone change, show that some resources would be created and destroyed and if i had chosen to apply that plan go on with that.
### Actual Behaviour
It first picked up the changed as if they were modification in place even if it's a change of availaibility zone which should not happen.

### Steps to Reproduce
terraform plan -out=tfplan
terraform apply tfplan

### Additional Context
We're using openstack as our IaaS. It might be an issue with the openstack provider but the output log said to post it here. 

### References
I've also opened and issue on terraform core https://github.com/hashicorp/terraform/issues/17835

**Comment by xocasdashdash** [comment] 2018-04-12 22:52
@jtopjian Ok!
I think it's when I add new values to an instance map, I'll see if i manage to create a reproducible example and share that in a gist.
Thanks!

**Comment by jtopjian** [comment] 2019-02-10 20:55
@xocasdashdash I'm going to close this issue since it hasn't been updated for a while. If you end up being able to reproduce this again, please let me know and I'll re-open it.

**Closed by jtopjian** 2019-02-10 20:55 UTC
