### ISSUE TITLE
compute_instance_v2 fails because subnet isn't created yet

### ISSUE THREAD

**Issue by hoover67** [terraform-providers/terraform-provider-openstack#796] opened 2019-07-12 12:24 UTC
### Terraform Version
Terraform v0.12.3

### Affected Resource(s)
- openstack_compute_instance_v2

### Terraform Configuration Files

... snip snip ....
resource "openstack_compute_instance_v2" "multi" {
  count           = var.counter
  name            = format("${var.instance_prefix}-%02d", count.index + 1)
  image_name      = var.image
  user_data       = file("scripts/centos7.sh")
  flavor_name     = var.flavor
  depends_on      = [openstack_networking_subnet_v2.lws]  # <-- this is a workaround
  key_pair        = openstack_compute_keypair_v2.terraform.name
  security_groups = ["ssh", "webservices"]
  network {
    name = var.network_name
  }
}
... snip snip... 

### Debug Output
Error: Error creating OpenStack server: Bad request with: [POST http://XXX.XXX.XXX.XXX:8774/v2.1/9d7efd87bb6e45acb73e007fcf3cd373/servers], error message: {"badRequest": {"message": "Network 18c78638-3075-4933-b2d5-78dd4c285895 requires a subnet in order to boot instances on.", "code": 400}}

### Expected Behavior
Terraform should recognize the dependency of the compute instances on the new subnet and only launch their creation once the fixed_ip subnet becomes available / is created successfully. 

### Actual Behavior
Instances are launched before the new subnet is available. Workaround: "depends_on" (see above) 

### Important Factoids
OpenStack Stein (built from packstack)  on CentOS 7.6 (self-hosted) 

### References
None

**Comment by jtopjian** [comment] 2019-07-12 12:41
@hoover67 Thank you for reporting this.

This isn't a bug per-se, but unfortunately expected behavior. The core problem is that there isn't anything obvious that links an instance to a network. An instance requires a subnet and a network has a subnet, but there isn't an explicit link between the two. This is why the `depends_on` is needed.

Alternatively, you can do:

```hcl
resource "openstack_compute_instance_v2" "instance_1" {
  ...

  network {
    uuid = "${openstack_networking_subnet_v2.subnet_1.network_id}"
  }
}
```

Because you're using the `network_id` attribute of the subnet resource, an implicit link is created between the two.

I'm going to close this issue but please let me know if you have any questions.

**Closed by jtopjian** 2019-07-12 12:41 UTC

**Comment by hoover67** [comment] 2019-07-12 12:44
Thanks for the clarification & sorry for the confusion. I'm rather new to this terraform thingy as you can tell, and what you describe makes perfect sense :) 

All the best & keep up the good work,

Uwe

**Comment by jtopjian** [comment] 2019-07-12 12:49
No problem at all - please let us know if you have any other questions, no matter how basic :)
