### ISSUE TITLE
Adding or Removing Ports Causes an uneeded destruction of an instance

### ISSUE THREAD

**Issue by JonathanNakandala** [terraform-providers/terraform-provider-openstack#156] opened 2017-11-14 14:47 UTC
Terraform destroys an instance when it doesn't need to.
### Terraform Version
Terraform v0.10.8

### Affected Resource(s)
Please list the resources as a list, for example:
- openstack_compute_instance_v2
- openstack_networking_port_v2

### Terraform Configuration Files
```hcl

provider "openstack" {
  user_name   = "${var.user_name}"
  password    = "${var.password}"
  tenant_name = "${var.tenant_name}"
  domain_name = "${var.domain_name}"
  auth_url    = "${var.auth_url}"
  region      = "${var.region}"
}

resource "openstack_compute_keypair_v2" "test-keypair" {
  name       = "test-keypair"
  public_key = "${var.public_key}"
}

resource "openstack_compute_instance_v2" "webserver-vm" {
  name            = "test-vm"
  image_id        = "${var.frontend_image_id}"
  flavor_id       = "${var.frontend_flavor_id}"
  key_pair        = "test-keypair"
  security_groups = ["default"]

  network {
    port = "${openstack_networking_port_v2.test-port-1.id}"
  }

  network {
    port = "${openstack_networking_port_v2.test-port-2.id}"
  }


}
resource "openstack_networking_port_v2" "test-port-1" {
  name           = "test-port-1"
  network_id     = "${openstack_networking_network_v2.Control-Network.id}"
  admin_state_up = "true"
}

resource "openstack_networking_port_v2" "test-port-2" {
  name           = "test-port-2"
  network_id     = "${openstack_networking_network_v2.Webserver-Network.id}"
  admin_state_up = "true"
}

resource "openstack_networking_subnet_v2" "Control-Subnet" {
  name       = "Control-Subnet"
  network_id = "${openstack_networking_network_v2.Control-Network.id}"
  cidr       = "192.168.2.0/24"
  ip_version = 4
  enable_dhcp = "true"
}

resource "openstack_networking_subnet_v2" "Webserver-Subnet" {
  name       = "Webserver-Subnet"
  network_id = "${openstack_networking_network_v2.Webserver-Network.id}"
  cidr       = "192.168.4.0/24"
  ip_version = 4
  enable_dhcp = "true"
}

resource "openstack_networking_network_v2" "Control-Network" {
  name           = "Control-Network"
  admin_state_up = "true"
}

resource "openstack_networking_network_v2" "Webserver-Network" {
  name           = "Webserver-Network"
  admin_state_up = "true"
}


```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Expected Behavior

In the example above, if you decide to delete one of the ports of the VM or add another one. 
It's possible in the Horizon GUI of Openstack or through the CLI to remove or add interfaces without requiring a destruction of the VM.

### Actual Behavior
Terraform will decide that the virtual machine must be destroyed and recreated as shown below.

`Terraform will perform the following actions:

-/+ openstack_compute_instance_v2.webserver-vm (new resource required)
      id:                         "c995eb9f-0d30-4db9-8ded-e38ea6878cb5" => <computed> (forces new resource)
      access_ip_v4:               "192.168.4.11" => <computed>
      access_ip_v6:               "" => <computed>
      all_metadata.%:             "0" => <computed>
      availability_zone:          "nova" => <computed>
      flavor_id:                  "42" => "42"
      flavor_name:                "m1.nano" => <computed>
      force_delete:               "false" => "false"
      image_id:                   "b9eb3d17-2bc5-421a-a999-4b4d6e6394b7" => "b9eb3d17-2bc5-421a-a999-4b4d6e6394b7"
      image_name:                 "cirros-0.3.5-x86_64-disk" => <computed>
      key_pair:                   "test-keypair" => "test-keypair"
      name:                       "webserver-vm" => "webserver-vm"
      network.#:                  "1" => "2" (forces new resource)
      network.0.access_network:   "false" => "false"
      network.0.fixed_ip_v4:      "192.168.4.11" => <computed>
      network.0.fixed_ip_v6:      "" => <computed>
      network.0.floating_ip:      "" => <computed>
      network.0.mac:              "fa:16:3e:9a:d8:69" => <computed>
      network.0.name:             "Webserver-Network" => <computed>
      network.0.port:             "9603926e-f113-4ccc-bd8a-c04fb22906d1" => "9603926e-f113-4ccc-bd8a-c04fb22906d1"
      network.0.uuid:             "2a0f4e19-e215-4f48-ac94-c8b74f2f291f" => <computed>
      network.1.access_network:   "" => "false"
      network.1.fixed_ip_v4:      "" => <computed>
      network.1.fixed_ip_v6:      "" => <computed>
      network.1.floating_ip:      "" => <computed>
      network.1.mac:              "" => <computed>
      network.1.name:             "" => <computed>
      network.1.port:             "" => "0468c8ab-20b6-4e42-a8cc-af643259a7c2" (forces new resource)
      network.1.uuid:             "" => <computed>
      region:                     "RegionOne" => <computed>
      security_groups.#:          "1" => "1"
      security_groups.3814588639: "default" => "default"
      stop_before_destroy:        "false" => "false"`

### Steps to Reproduce
1. Take the example given above and deploy it
2. Remove or add a port to the VM
3. Terraform will have to destroy the VM

### Important Factoids
Tested this on Devstack.

**Comment by jtopjian** [comment] 2017-11-14 15:41
@JonathanNakandala Thank you for reporting this.

> In the example above, if you decide to delete one of the ports of the VM or add another one.
It's possible in the Horizon GUI of Openstack or through the CLI to remove or add interfaces without requiring a destruction of the VM.

At this time this is expected behavior. The upstream Go library (gophercloud) does not yet support attaching and detaching ports/interfaces of instances. Since that functionality is not possible, the only appropriate thing to do is recreate the instance.

I'll leave this issue open and mark it as an upstream enhancement.

**Comment by anlutro** [comment] 2017-12-08 09:41
I might be interested in implementing this. Could someone point me to code of the terraform plugin or gophercloud that prevents attaching/detaching of ports/interfaces on instances?

**Comment by jtopjian** [comment] 2017-12-08 16:51
@anlutro coincidentally the ability to attach and detach interfaces has recently been added to Gophercloud in the last week. You can check the commit history at https://github.com/gophercloud/gophercloud or the closed PRs.

Implementing this would be appreciated, but it's going to be a difficult one. The `openstack_compute_instance_v2` resource was created before any of the `os-attach-interface` extensions were available so there's a good number of workarounds in place to account for it (see the entire `openstack/compute_instance_v2_networking.go` file in this repo for example :) The best option is to see how all of that can be refactored to take advantage of the `os-attach-interface` extension. 

Given the amount of background knowledge needed for this, I can definitely take a look at it soon.

**Comment by anlutro** [comment] 2017-12-08 17:34
I'll take your word for it and leave it be. If/when there's a pull request or something I'd be happy to compile and help with testing.

**Comment by jtopjian** [comment] 2019-02-10 20:32
We added support for [`openstack_compute_interface_attach_v2`](https://www.terraform.io/docs/providers/openstack/r/compute_interface_attach_v2.html) a few months ago which should resolve this issue. I apologize for the delay in mentioning this.

I'm going to close this issue, but please let me know if anyone would like to discuss this further.

**Closed by jtopjian** 2019-02-10 20:32 UTC
Labels: enhancement, upstream
